# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
      vb.cpus = 4
      vb.memory = 16384
  end

  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "file", source: "example.c", destination: "example.c"
  config.vm.provision "file", source: "README.md", destination: "README.md"
  config.vm.provision "file", source: "LAVA", destination: "LAVA"

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get update
    sudo apt install -y python clang libacl1-dev libcap-dev libselinux1-dev libgmp-dev
    sudo apt install -y libtool-bin automake bison libglib2.0-dev flex

    echo "kernel.core_pattern = core"|sudo tee /etc/sysctl.d/99-qsym.conf
    echo "kernel.yama.ptrace_scope = 0"|sudo tee -a /etc/sysctl.d/99-qsym.conf
    sudo sysctl --system

    # install pip
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    sudo python get-pip.py
    rm get-pip.py

    # install qsym
    git clone https://github.com/sslab-gatech/qsym

    pushd qsym
    ./setup.sh
    sudo pip install .
    popd

    # install afl
    wget http://lcamtuf.coredump.cx/afl/releases/afl-2.52b.tgz
    tar -zxvf afl-2.52b.tgz
    rm afl-2.52b.tgz
    pushd afl-2.52b
    make
    cd qemu_mode
    ./build_qemu_support.sh
    popd
  SHELL
end
